version: '3.3'

services:
  applibros:
    container_name: appLibros
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/mydatabase

  db:
    container_name: base_de_datos
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db

volumes:
  db-data: